db:
  image: postgres
web:
  build: .
  command: bash -c "sleep 3 && python manage.py migrate && sleep 3 && python manage.py runserver 0.0.0.0:8000"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db